apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: spartakus
  name: spartakus-volunteer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spartakus-volunteer
    spec:
      containers:
      - args:
        - volunteer
        - --cluster-id=$(usageId)
        - --database=https://stats-collector.kubeflow.org
        image: registry.cn-shenzhen.aliyuncs.com/shikanon/google_containers.spartakus-amd64:v1.1.0
        name: volunteer
      serviceAccountName: spartakus
